package stringcheesedevs.android.apps.com.trailblazer.Utils;

import android.content.Context;

import stringcheesedevs.android.apps.com.trailblazer.Models.Artist;
import stringcheesedevs.android.apps.com.trailblazer.Models.DaoSession;
import stringcheesedevs.android.apps.com.trailblazer.TBApplication;

public class NamesUtils {


    public static String[] names = {"10 cc"
            ,"10 Years"
            ,"2 Chainz"
            ,"3 Doors Down"
            ,"4minute (South Korea)"
            ,"4 Strings"
            ,"The 1975"
            ,"5 Seconds of Summer"
            ,"50 Cent"
            ,"6ix9ine"
            ,"Aaliyah"
            ,"Alsou"
            ,"ABBA"
            ,"Abandon All Ships"
            ,"The All-American Rejects"
            ,"The Airborne Toxic Event"
            ,"Ace Hood"
            ,"Ace of Base"
            ,"Adassa"
            ,"Admiral T"
            ,"Afrojack"
            ,"AGA (Universal Music Hong Kong)"
            ,"Airbourne"
            ,"Aitana"
            ,"AJR"
            ,"Akon"
            ,"Alan Tam"
            ,"Alesso"
            ,"Alexander Rybak"
            ,"Alison Krauss"
            ,"Alphabeat"
            ,"All That Remains"
            ,"All Time Low"
            ,"Allstar Weekend"
            ,"Aloe Blacc"
            ,"Alter Bridge"
            ,"Amaranthe"
            ,"Angels & Airwaves"
            ,"Anthrax"
            ,"Alice Nine"
            ,"Alphaville"
            ,"AFI"
            ,"After Midnight Project"
            ,"Alessia Cara"
            ,"Amy Holland"
            ,"Amy Winehouse"
            ,"Ana Guerra (Spain)"
            ,"Ana Moura (Portugal)"
            ,"Anastacia"
            ,"Anberlin"
            ,"Andrea Bocelli"
            ,"Anggun"
            ,"Any Gabrielly (Walt Disney Records)"
            ,"A-Mei"
            ,"Apink (South Korea)"
            ,"Apocalyptica"
            ,"Armin Van Buuren"
            ,"Arnaldo Antunes"
            ,"Ariana Grande"
            ,"A R Rahman"
            ,"Aqua"
            ,"The Aquabats"
            ,"As It Is"
            ,"Ashanti"
            ,"Ashlee Simpson"
            ,"Asher Roth"
            ,"Ashes Divide"
            ,"Ashton Shepherd"
            ,"Asia"
            ,"Astrid S"
            ,"Asuca Hayashi"
            ,"Atreyu"
            ,"Audioslave"
            ,"August Burns Red"
            ,"Auliʻi Cravalho (Walt Disney Records)"
            ,"Aura Dione"
            ,"Avenged Sevenfold"
            ,"Avicii"
            ,"Aya Hirano"
            ,"Ayọ"
            ,"Babyface"
            ,"BG"
            ,"Baba Saad"
            ,"Babi Xavier"
            ,"Base Ball Bear"
            ,"Bastille"
            ,"Barei"
            ,"BEAST (South Korea)"
            ,"Bee Gees"
            ,"The Beatles"
            ,"Backstreet Boys"
            ,"Belinda Peregrín"
            ,"Beni Arashiro"
            ,"Benny Benassi"
            ,"Billy Blue"
            ,"Bishop Lamont"
            ,"Big Bang (South Korea)"
            ,"Big Sean"
            ,"Big Time Rush"
            ,"Biquini Cavadão"
            ,"Birdman"
            ,"Björk"
            ,"Blue"
            ,"Buckcherry"
            ,"The Black Eyed Peas"
            ,"Blackpink (South Korea)"
            ,"Black Tide"
            ,"Black Veil Brides"
            ,"Blaxy Girls"
            ,"Blink182"
            ,"Blue October"
            ,"Blood Raw"
            ,"Bloodhound Gang"
            ,"Bloom 06"
            ,"Bob Marley"
            ,"Bob Sinclar"
            ,"Bobby McFerrin"
            ,"Bohemia"
            ,"Bombay Rockers"
            ,"Bon Jovi"
            ,"Bond (band)"
            ,"Bone Thugs-n-Harmony"
            ,"Boston"
            ,"The Bravery"
            ,"Bradley Cooper"
            ,"Brand New"
            ,"Brandy"
            ,"Breaking Benjamin"
            ,"Bridgit Mendler"
            ,"Bruna Guerin (Walt Disney Records)"
            ,"Bruno Campos (Walt Disney Records)"
            ,"Bruno & Marrone (Since 2017)"
            ,"Bryan Adams"
            ,"Brynn Cartelli"
            ,"Busta Rhymes"
            ,"Butthole Surfers"
            ,"BtoB (South Korea)"
            ,"BTS (South Korea)"
            ,"Boyzone"
            ,"Boys Republic (South Korea)"
            ,"Bow Wow"
            ,"Bullet for My Valentine"
            ,"Bun B"
            ,"Buraka Som Sistema"
            ,"Bushido"
            ,"Camille"
            ,"Caparezza"
            ,"Capital Cities"
            ,"Carlinhos Brown"
            ,"Carlos Alazraqui (Walt Disney Records)"
            ,"Carlos do Carmo"
            ,"Carly Rae Jepsen"
            ,"The Carpenters"
            ,"Carrie Underwood"
            ,"The Cranberries"
            ,"The Crystal Method"
            ,"The Cure"
            ,"Cascada"
            ,"Cassadee Pope"
            ,"Cássia Eller"
            ,"Cassie"
            ,"Cash Cash"
            ,"Cassper Nyovest"
            ,"Cazuza"
            ,"Cedric Gervais"
            ,"Cepeda (singer)"
            ,"Cinema Bizarre (band)"
            ,"City Boy"
            ,"Craig David"
            ,"Chamillionaire"
            ,"Charlee"
            ,"Charles Aznavour"
            ,"Charles Hamilton"
            ,"Chay Suede"
            ,"The Chemical Brothers"
            ,"Chenoa"
            ,"Cher"
            ,"Cher Lloyd"
            ,"Cherish (Since 2006)"
            ,"Cheryl"
            ,"Chester French"
            ,"Chilla Kiana (Indonesia)"
            ,"Children Collide"
            ,"Chicane"
            ,"Children of Bodom"
            ,"Chris Cornell"
            ,"Chris Daughtry"
            ,"Chitãozinho & Xororó"
            ,"Cimorelli"
            ,"Claude Kelly"
            ,"Coal Chamber"
            ,"Christina Milian"
            ,"Christina Grimmie"
            ,"Chrisette Michelle"
            ,"Chumbawamba"
            ,"Clementino (since 2013)"
            ,"Clouds"
            ,"Club Dogo"
            ,"Colbie Caillat"
            ,"Colby O'Donis"
            ,"Coldplay (Former)"
            ,"Common"
            ,"Corson"
            ,"Cory Gunz"
            ,"Counting Crows"
            ,"Clique Girlz"
            ,"Charles Hamilton"
            ,"Crashdïet"
            ,"Ciara"
            ,"Cine (2009-2012)"
            ,"CPM 22"
            ,"Crazy Frog"
            ,"Crazy Town"
            ,"Creamy"
            ,"Crystal Castles"
            ,"Crystal Kay"
            ,"Curren$y"
            ,"Cut Copy"
            ,"Cyndi Lauper"
            ,"DeLon"
            ,"D12"
            ,"D. Brown"
            ,"Da Mouth"
            ,"Daddy Yankee"
            ,"Daiyan Trisha (Universal Music Malaysia)"
            ,"Dan Black"
            ,"Dan Reynolds"
            ,"Dancemania"
            ,"Daniel Merriweather"
            ,"Danzig"
            ,"Dark Tranquility"
            ,"Darren Espanto (Philippines)"
            ,"David Banner"
            ,"David Bisbal"
            ,"David Bustamante"
            ,"David Fonseca"
            ,"David Gray"
            ,"David Guetta (Former)"
            ,"David Nail"
            ,"Darude"
            ,"Days Difference"
            ,"Dead by April"
            ,"Debbie Harry"
            ,"Dave Matthews Band"
            ,"Deadmau5"
            ,"Death (Canada)"
            ,"Dean"
            ,"Deep Purple"
            ,"Demi Lovato"
            ,"Denez Prigent"
            ,"Depeche Mode"
            ,"Desiigner"
            ,"Diamond Platnumz"
            ,"Dido"
            ,"Dtidrik Solli-Tangenh"
            ,"Die Antwoord"
            ,"Dierks Bentley"
            ,"Dire Straits"
            ,"Dirty Vegas"
            ,"Dima Bilan"
            ,"Divine Brown"
            ,"Dizzee Rascal"
            ,"DJ Khaled"
            ,"DJ Snake"
            ,"DMX"
            ,"DNCE"
            ,"Doda"
            ,"Dolly Parton"
            ,"Dolores O'Riordan"
            ,"Don Omar"
            ,"Donna Lewis"
            ,"Double You"
            ,"The-Dream"
            ,"Dreams Come True (Since 1997)"
            ,"DragonForce (Finland)"
            ,"Dragonette"
            ,"Drake"
            ,"Drake Bell (2006–2009)"
            ,"The Drums"
            ,"Dr. Dre"
            ,"Duck Sauce"
            ,"Duffy"
            ,"Duke Dumont"
            ,"Dulce Maria"
            ,"Duran Duran"
            ,"DVDA"
            ,"Dwayne Johnson (Walt Disney Records)"
            ,"Dzeko"
            ,"The Eagles"
            ,"Eason Chan"
            ,"Easton Corbin"
            ,"Edoardo Bennato"
            ,"Eels"
            ,"Eiffel 65"
            ,"Elhaida Dani"
            ,"Elena Paparizou (Greece)"
            ,"Ellie Goulding"
            ,"Elton John"
            ,"Emily Blunt (Walt Disney Records)"
            ,"Eminem"
            ,"Emma Bunton"
            ,"Emmelie de Forest"
            ,"Enigma"
            ,"Enca"
            ,"Enrique Iglesias"
            ,"Enya (Geffen Records)"
            ,"Emma's Imagination"
            ,"Empire of the Sun"
            ,"Enter Shikari"
            ,"Equinox (Bulgaria)"
            ,"Eric Papilaya (Austria)"
            ,"Eric Whitacre"
            ,"Eriko Tamura"
            ,"Eros Ramazzotti"
            ,"Erykah Badu"
            ,"Escape the Fate"
            ,"Estelle"
            ,"Eugenio Bennato"
            ,"Evanescence"
            ,"Exodus"
            ,"Fabolous"
            ,"Fabri Fibra"
            ,"Faithless"
            ,"Fall Out Boy"
            ,"FanFan"
            ,"Fang Wu"
            ,"Far East Movement"
            ,"Faryl Smith"
            ,"Fazura (Universal Music Malaysia)"
            ,"Felli Fel"
            ,"Fergie"
            ,"Fever Ray"
            ,"The Fevers"
            ,"Finger Eleven"
            ,"Fish Leong"
            ,"Fisherman's Friends"
            ,"Flaw"
            ,"Flipsyde"
            ,"Flo Rida"
            ,"Florence and the Machine"
            ,"Florence Welch"
            ,"Forever the Sickest Kids"
            ,"Franco Battiato"
            ,"Frankie Goes to Hollywood"
            ,"French Montana"
            ,"Fresno (2008-2010)"
            ,"Gal Gadot (Walt Disney Records)"
            ,"Game"
            ,"Gary Allan"
            ,"George Benson"
            ,"George Lam"
            ,"George Michael"
            ,"George Harrison"
            ,"George Strait"
            ,"Ghostface Killah"
            ,"Gianna Nannini"
            ,"Gin Lee (Universal Music Hong Kong)"
            ,"Giorgio Moroder"
            ,"Girlicious"
            ,"Girls' Generation (South Korea)"
            ,"Glasses Malone"
            ,"Gloria Jessica (Indonesia)"
            ,"Gloria Trevi"
            ,"Go Back to the Zoo"
            ,"Godsmack"
            ,"The Go-Go's"
            ,"Gorillaz"
            ,"Gotye"
            ,"Great White"
            ,"Guns N' Roses"
            ,"Gwen Stefani"
            ,"Hacken Lee"
            ,"Haddaway"
            ,"Hailee Steinfeld"
            ,"Halsey"
            ,"Hedley"
            ,"Helena Paparizou"
            ,"Helene Fischer (Germany)"
            ,"Hellogoodbye"
            ,"Hevo 84"
            ,"Hide"
            ,"HIM"
            ,"Hinder"
            ,"Hins Cheung"
            ,"Holly Williams"
            ,"Mr Hudson"
            ,"Hoobastank"
            ,"Hollywood Monsters (Canada)"
            ,"Hollywood Undead"
            ,"Hot Rod"
            ,"Hot Chelle Rae"
            ,"Hozier"
            ,"Hyper Crush"
            ,"G.NA (South Korea)"
            ,"I Blame Coco"
            ,"I Prevail"
            ,"Il Volo"
            ,"Ice Nine Kills"
            ,"Ida Maria"
            ,"Idina Menzel (Walt Disney Records)"
            ,"Iggy Azalea"
            ,"Ilya"
            ,"Imagine Dragons"
            ,"India Arie"
            ,"In Dread Response"
            ,"Inna"
            ,"Ivete Sangalo"
            ,"Incubus"
            ,"Infected Mushroom"
            ,"Inner Circle"
            ,"Infinite (South Korea)"
            ,"Irene Cara"
            ,"Iron Maiden"
            ,"Ironik"
            ,"Isaac Hayes"
            ,"Israel Kamakawiwoʻole"
            ,"Institute"
            ,"IU (South Korea)"
            ,"Jacky Cheung"
            ,"Jack Jersey"
            ,"Jack Johnson"
            ,"The Jackson 5 (1964-1974)"
            ,"Jacob Collier"
            ,"Jada"
            ,"Jadakiss"
            ,"Jadyn Maria"
            ,"Jae Millz"
            ,"James Blunt"
            ,"James Morrison"
            ,"Jamie Principle"
            ,"Jan Hammer"
            ,"Jane Birkin"
            ,"Jason Dy (Philippines)"
            ,"Jay Sean"
            ,"Jay Hardway"
            ,"Jay-Z"
            ,"Ja Rule"
            ,"JD McCrary"
            ,"Jean-Michel Jarre"
            ,"Jedward"
            ,"Jemaine Clement (Walt Disney Records)"
            ,"Jeremih"
            ,"Jessie J"
            ,"Jessie James"
            ,"Jessica Sanchez"
            ,"Jennifer Lopez"
            ,"Jessica Mauboy"
            ,"Jessica Simpson"
            ,"Jin Au-Yeung"
            ,"Joana Zimmer"
            ,"Joe Jonas"
            ,"Joe Walsh"
            ,"John Lennon"
            ,"John Mayer"
            ,"Johnny Cash"
            ,"Johnta Austin"
            ,"Jonas Blue"
            ,"Josh Gracin"
            ,"Joe Satriani"
            ,"Jordan Chan"
            ,"Josh Gad (Walt Disney Records)"
            ,"Josh Turner"
            ,"Josh Dun"
            ,"Jovanotti"
            ,"Juanes"
            ,"Juan Karlos Labajo (Philippines)"
            ,"Juelz Santana"
            ,"Julia Michaels (Walt Disney Records)"
            ,"Justin Bieber"
            ,"Jacquees"
            ,"J-Xtreme (South Africa)"
            ,"Kaitlyn Maher"
            ,"Kanye West"
            ,"Kardinal Offishall"
            ,"KARA (South Korea)"
            ,"Karen Mok (Hong Kong, China)"
            ,"Karol Sevilla (Walt Disney Records)"
            ,"Karkadan"
            ,"Katharine McPhee"
            ,"Kat DeLuna"
            ,"Kate Earl"
            ,"Keith David (Walt Disney Records)"
            ,"Keith Urban"
            ,"Kelis"
            ,"Kelly Chen (Universal Music Hong Kong)"
            ,"Kendrick Lamar"
            ,"Keri Hilson"
            ,"Keshia Chanté"
            ,"Kevin Rudolf"
            ,"Keyshia Cole"
            ,"Kid Abelha (Since 2000)"
            ,"Kid Cudi"
            ,"Kidz Bop Kids"
            ,"The Killers"
            ,"Kim Hyun Joong"
            ,"Kim Wilde"
            ,"Kiss"
            ,"K.I.Z"
            ,"The Knife"
            ,"Kris Wu"
            ,"Krista Siegfrids (Finland)"
            ,"Kristen Bell (Walt Disney Records)"
            ,"Kuana Torres Kahele"
            ,"Kyu Sakamoto"
            ,"Lady Antebellum"
            ,"Lady Gaga"
            ,"Lana Del Rey"
            ,"Lifer"
            ,"Lionel Richie"
            ,"Lobão"
            ,"Logic"
            ,"Lorde"
            ,"La Roux"
            ,"Ladyhawke"
            ,"Lawson"
            ,"Lee Ann Womack"
            ,"Legião Urbana"
            ,"Leslie Cheung"
            ,"Lights"
            ,"Lil Ru"
            ,"Lil Scrappy"
            ,"Lil Twist"
            ,"Lil' Kim"
            ,"Lil Mosey"
            ,"Lil Wayne"
            ,"Lil Yachty"
            ,"Lin-Manuel Miranda (Walt Disney Records)"
            ,"LMFAO"
            ,"The Lonely Island"
            ,"Lucenzo"
            ,"Ludo"
            ,"Ludacris"
            ,"Luke Bryan"
            ,"Lulu Santos"
            ,"The Lumineers"
            ,"LUNA SEA"
            ,"Limp Bizkit"
            ,"Lim Hyung Joo"
            ,"Lena Meyer-Landrut"
            ,"Luísa Sonza (Walt Disney Records)"
            ,"Lyca Gairanod (Philippines)"
            ,"Mack 10"
            ,"Mack Maine"
            ,"Madonna (Since 2010)"
            ,"The Maine"
            ,"Mamonas Assassinas"
            ,"Mannie Fresh"
            ,"Manu Gavassi"
            ,"Mao Denda"
            ,"Marcelo D2"
            ,"Marky"
            ,"Mark Oliver Everett"
            ,"Mark Salling"
            ,"Martin Garrix"
            ,"Martin Solveig"
            ,"Mallary Hope"
            ,"Maria Isabel"
            ,"Maria Dwi Permata Simorangkir (Universal Music Indonesia)"
            ,"Mariah Carey"
            ,"Mariana Elisabetsky (Walt Disney Records)"
            ,"Marilyn Manson"
            ,"Maroon 5"
            ,"Masaharu Fukuyama"
            ,"Momoland (South Korea)"
            ,"Marracash"
            ,"Marta Sánchez"
            ,"Massacration"
            ,"Maureen McGovern"
            ,"MaxBoys"
            ,"Kevin McHale"
            ,"Meat Loaf"
            ,"Megumi Hayashibara"
            ,"Mel Fronckowiak"
            ,"Melanie Fiona"
            ,"Melissa Etheridge"
            ,"Melody Gardot"
            ,"Method Man"
            ,"Megadeth"
            ,"Metallica"
            ,"Metal Church"
            ,"MIA"
            ,"Michael Jackson (1964-1974)"
            ,"Michael Sarver"
            ,"Migos"
            ,"Miguel (Geffen Records)"
            ,"Mihimaru GT"
            ,"Mika"
            ,"Mike Posner"
            ,"Miki Imai"
            ,"Miley Cyrus"
            ,"Milton Nascimento"
            ,"Miyavi"
            ,"Miss A (Since 2012)"
            ,"Mohamed Mounir"
            ,"Momoiro Clover"
            ,"Mr Hudson"
            ,"Mumford & Sons"
            ,"Muse"
            ,"Mushroomhead"
            ,"Ms. Triniti"
            ,"Morteza Pashaei"
            ,"Mýa"
            ,"Mylène Farmer"
            ,"Nadia Nakai (South Africa)"
            ,"The Naked and Famous"
            ,"Nami Tamaki"
            ,"Namie Amuro"
            ,"Nas"
            ,"Nasty C (South Africa)"
            ,"Natalia Lafourcade (Walt Disney Records)"
            ,"Nav"
            ,"Natalia Kills"
            ,"N-Dubz"
            ,"Ne-Yo"
            ,"Nelly"
            ,"Nelly Furtado"
            ,"Neon Trees"
            ,"N.E.R.D"
            ,"Nicole Scherzinger"
            ,"Nick Cave"
            ,"Nickelback (Canada)"
            ,"Nicki Minaj"
            ,"Nicola Roberts"
            ,"Nicole Scherzinger"
            ,"Nightwish"
            ,"Nine Inch Nails"
            ,"Noize MC (2006–2008)"
            ,"Noizy (Albania)"
            ,"Nolwenn Leroy (France)"
            ,"Nimo [de] (Germany)"
            ,"NOFX"
            ,"The Notorious B.I.G."
            ,"NX Zero (2006–2012)"
            ,"O–P"
            ,"Of Monsters and Men"
            ,"Oh Wonder"
            ,"Oingo Boingo"
            ,"OneRepublic"
            ,"Oomph!"
            ,"Orianthi"
            ,"Emily Osment"
            ,"The Offspring"
            ,"The Outfield (1990-1992)"
            ,"Owl City"
            ,"O-Town (A&M Records) (Japan/Germany/France)"
            ,"P.O.D."
            ,"Papa Roach"
            ,"The Parlotones"
            ,"Patrick Juvet"
            ,"Paul McCartney"
            ,"Paul Engemann"
            ,"Paula Fernandes"
            ,"Paulina Rubio"
            ,"Pedro Abrunhosa (Portugal)"
            ,"Pet Shop Boys (US And Canada)"
            ,"Peter Bjorn and John"
            ,"Katy Perry"
            ,"Pierce the Veil"
            ,"Pixie Lott"
            ,"Perfume"
            ,"Phantogram"
            ,"Phil Collins (Walt Disney Records)"
            ,"Pink Floyd"
            ,"Play"
            ,"Playaz Circle"
            ,"The Police"
            ,"Polina Gagarina"
            ,"Post Malone"
            ,"Pussycat Dolls"
            ,"Parachute"
            ,"The Presets"
            ,"Prima J"
            ,"Prudence Liew"
            ,"PSY (since 2012) (South Korea)"
            ,"Queen (since 2011)"
            ,"Queens of the Stone Age"
            ,"Queensrÿche"
            ,"R5"
            ,"Ra"
            ,"Rabbi Shergill"
            ,"Radwimps"
            ,"Rae Sremmurd"
            ,"Rainbow (South Korea)"
            ,"Rainer + Grimm"
            ,"Rammstein"
            ,"The Ramones"
            ,"Randy Newman"
            ,"Raul Seixas"
            ,"Raven-Symoné"
            ,"Razorlight"
            ,"Reba McEntire"
            ,"Rebeldes"
            ,"Redman"
            ,"Red Hot Chili Peppers (1983-1990)"
            ,"Red Velvet (South Korea)"
            ,"Renato Russo"
            ,"Rev Theory"
            ,"Rick Astley"
            ,"Rick Ross"
            ,"Rich Boy"
            ,"Rihanna"
            ,"Ringo Sheena"
            ,"Ringo Starr"
            ,"Rise Against"
            ,"Rob Paulsen (Walt Disney Records)"
            ,"Rob Zombie"
            ,"Robbie Williams"
            ,"Roberto Garcia (Walt Disney Records)"
            ,"Robyn"
            ,"Rod Stewart (since 2012)"
            ,"Roi Méndez"
            ,"Rooney"
            ,"Ross Lynch"
            ,"RPM"
            ,"Rubber Soul"
            ,"Ryan Tedder"
            ,"Serena Ryder"
            ,"Sakis Rouvas (Greece)"
            ,"Sakura Gakuin"
            ,"Samsons (Indonesia)"
            ,"Sam Smith"
            ,"Samved (India)"
            ,"Sandy"
            ,"Sandy & Júnior"
            ,"Sandy Lam"
            ,"Sara Paula Gómez Arias (Walt Disney Records)"
            ,"Sarah Silverman (Walt Disney Records)"
            ,"The Saturdays"
            ,"Satyricon"
            ,"Saulo Vasconcelos (Walt Disney Records)"
            ,"Saving Grace"
            ,"Scooter"
            ,"Scorpions"
            ,"Sean Garrett"
            ,"Sean Paul"
            ,"Seeb"
            ,"Seether"
            ,"Serge Gainsbourg"
            ,"Sergio Godinho (Portugal)"
            ,"Serebro (Worldwide/Japan)"
            ,"Seth MacFarlane"
            ,"Shaggy"
            ,"Shakira (Walt Disney Records)"
            ,"Shane Filan"
            ,"Shania Twain"
            ,"Shareefa"
            ,"Shawn Mendes"
            ,"SHINee (South Korea)"
            ,"Shontelle"
            ,"Sia"
            ,"Sigma"
            ,"Sigrid"
            ,"Silentó"
            ,"Simone & Simaria (Since 2015)"
            ,"Simple Minds"
            ,"Simple Plan (Lava Records)"
            ,"Siti Nurhaliza (Universal Music Malaysia)"
            ,"Seiko Matsuda"
            ,"Selena Gomez"
            ,"Smile.dk"
            ,"Slash"
            ,"Slayer"
            ,"Smash Mouth"
            ,"Snow Patrol"
            ,"Sodagreen (Taiwan)"
            ,"Sonata Arctica"
            ,"Soraya Arnelas"
            ,"Soulja Boy"
            ,"Stevie Wonder"
            ,"Sunidhi Chauhan (India)"
            ,"Sugarland"
            ,"Space Cowboy"
            ,"Spice Girls"
            ,"Spose"
            ,"Stefanie Sun"
            ,"Steve Winwood"
            ,"Sting"
            ,"Street Drum Corps"
            ,"Steel Panther"
            ,"Stromae"
            ,"Sum 41"
            ,"Super Junior (South Korea)"
            ,"Super Monkey's"
            ,"Supertramp"
            ,"Sully Erna"
            ,"Svoy"
            ,"Swae Lee"
            ,"SZA"
            ,"T Lopez"
            ,"T-ara (South Korea)"
            ,"The Stunners"
            ,"Tessanne Chin"
            ,"Taio Cruz"
            ,"Takako Matsu"
            ,"Take That"
            ,"Tamar Braxton"
            ,"Tami Chynn"
            ,"Tamta (Greece)"
            ,"Tarja"
            ,"Taylor Swift"
            ,"Tears for Fears"
            ,"Teresa Teng (Japan Only)"
            ,"Teyana Taylor"
            ,"Thirty Seconds to Mars"
            ,"Tiago Abravanel (Walt Disney Records)"
            ,"Tiago Bettencourt (Portugal)"
            ,"Tiësto"
            ,"Tihuana"
            ,"Tim McGraw"
            ,"Tina Parol (Walt Disney Records)"
            ,"Tinchy Stryder"
            ,"Tiziano Ferro (Italy)"
            ,"Tono Rosario"
            ,"Toni Braxton"
            ,"Tokio Hotel"
            ,"Tom Tom Club"
            ,"Tony Anselmo (Walt Disney Records)"
            ,"Toquinho"
            ,"Tori Kelly"
            ,"Tove Lo"
            ,"Trippie Redd"
            ,"Troye Sivan"
            ,"t.A.T.u."
            ,"The Tragically Hip"
            ,"Tupac Shakur"
            ,"Twelve Girls Band"
            ,"Tyga"
            ,"TYP"
            ,"Tyson Ritter"
            ,"Tyler Joseph"
            ,"U2"
            ,"Ultrabeat"
            ,"Unladylike"
            ,"Utada"
            ,"Vacca"
            ,"The Vamps"
            ,"Vangelis"
            ,"Van Halen"
            ,"Vanessa Carlton"
            ,"The Veer Union"
            ,"Venom"
            ,"Vince Gill"
            ,"Volbeat"
            ,"Wale"
            ,"Cyndi Wang"
            ,"The Wanted"
            ,"Wanting Qu"
            ,"WaT"
            ,"The Weeknd"
            ,"Weezer"
            ,"Westlife"
            ,"The Who"
            ,"Wisin & Yandel"
            ,"Wolfmother"
            ,"Wyclef Jean"
            ,"Willy Northpole"
            ,"Will Pan"
            ,"will.i.am"
            ,"Within Temptation"
            ,"Wiz Khalifa (Rostrum Records)"
            ,"Wonder Girls (South Korea)"
            ,"Wu Bai"
            ,"Xonia"
            ,"Vanness Wu"
            ,"Xuxa"
            ,"Yasuko Matsuyuki"
            ,"Yazz"
            ,"Yeah Yeah Yeahs"
            ,"Years & Years"
            ,"Yelle"
            ,"Yellow Magic Orchestra"
            ,"Yngwie Malmsteen"
            ,"Yohio"
            ,"Yoko Ono"
            ,"Young Jeezy"
            ,"Your Favorite Martian"
            ,"Yū Hayami"
            ,"Yumi Matsutoya"
            ,"Yung L.A."
            ,"Yves Larock"
            ,"Zana Messia"
            ,"Zascha Moktan"
            ,"Zélia Duncan (1998-2012)"
            ,"Zendaya"
            ,"Zucchero"   };


public NamesUtils(Context c){
        DaoSession daoSession = ((TBApplication)c).getDaoSession();
        if(daoSession.getArtistDao().loadAll().size()==0){
            for(String s:names){
                Artist a = new Artist();
                a.setName(s);
                daoSession.getArtistDao().save(a);
            }
        }
    }
}
